import type {Metadata} from "next";
import Link from "next/link";
import {ArrowUpRight,BookOpenText,BriefcaseBusiness,ExternalLink,FileText} from "lucide-react";
import {featuredPublication} from "@/lib/content";
export const metadata:Metadata={title:"Selected work & publications",description:"Verified published economics commentary, research experience and monitoring work by Dennis Richard."};
export default function WorkPage(){
 return <main id="main">
 <section className="subhero"><div className="container"><div className="eyebrow">SELECTED EXPERIENCE / PUBLICATIONS</div><h1>Evidence from<br/><em>real work.</em></h1><p>Published writing, academic research and professional contributions, presented with attention to the limits of the underlying evidence.</p></div></section>
 <section className="section section-white"><div className="container work-layout"><aside className="sticky-index"><span>ON THIS PAGE</span><a href="#publication">01 — Commentary</a><a href="#infrastructure">02 — Infrastructure</a><a href="#dissertation">03 — Research</a><a href="#consulting">04 — Consulting</a></aside>
 <div className="case-studies">
 <article id="publication" className="case-study"><div className="case-overline"><BookOpenText size={18}/> 01 / PUBLISHED ECONOMIC COMMENTARY</div><h2>Malawi&apos;s fuel queues: the global picture, domestic pressures and policy context.</h2><p>In October 2026, The Maravi Post published my economic commentary examining external energy-market pressures, domestic foreign-exchange constraints and differences in policy context across government periods.</p><div className="detail-pair"><div><span>PUBLISHER</span><strong>The Maravi Post</strong></div><div><span>DATE</span><strong>4 October 2026</strong></div><div><span>FORMAT</span><strong>Economic commentary, not peer reviewed</strong></div></div><a className="underlined-link" href={featuredPublication.href} target="_blank" rel="noopener noreferrer">Read the published article <ExternalLink size={17}/></a></article>
 <article id="infrastructure" className="case-study"><div className="case-overline"><BriefcaseBusiness size={18}/> 02 / PUBLIC-SECTOR EXPERIENCE</div><h2>Infrastructure monitoring, data integrity and reporting.</h2><p>As a planning intern at Malawi&apos;s Roads Authority (June 2023–July 2024), I supported the maintenance and validation of an infrastructure project tracker covering over 800 access-road project records, and contributed to 12 quarterly and one annual planning report.</p><div className="detail-pair"><div><span>CORE CONTRIBUTIONS</span><strong>Tracking, record validation, planning and reporting support</strong></div><div><span>METHODS</span><strong>Excel, document review, structured reporting</strong></div></div><p className="evidence-note">These are institutional team-work contributions, not claims of having independently delivered 800 infrastructure projects or authored reports alone. Internal organizational files are not published.</p></article>
 <article id="dissertation" className="case-study"><div className="case-overline"><FileText size={18}/> 03 / UNDERGRADUATE RESEARCH</div><h2>Analyzing the effects of oil prices on the exchange rate in Malawi.</h2><p>My Economics dissertation at the Catholic University of Malawi investigated the relationship between international oil prices and the exchange rate, using applied time-series and autoregressive distributed lag methods.</p><div className="detail-pair"><div><span>RESEARCH AREA</span><strong>Macroeconomics and exchange-rate dynamics</strong></div><div><span>METHOD</span><strong>Time-series econometric analysis</strong></div></div><p className="evidence-note">Regression tables and numerical results will appear only after the original dissertation data and results have been verified for public release.</p></article>
 <article id="consulting" className="case-study"><div className="case-overline"><BriefcaseBusiness size={18}/> 04 / APPLIED RESEARCH</div><h2>Research, analysis and technical communication.</h2><p>My work at RichPen Ink Consultancy has involved research design, structured data analysis, monitoring frameworks and technical writing. Volunteer research activities have also supported my interest in trade and development policy.</p><p className="evidence-note">Client-sensitive work, identifiable participant records and confidential institutional data are excluded. Only independently created or publication-cleared examples will be added.</p></article>
 <div className="next-panel"><strong>Where the work goes next.</strong><p>My future projects will connect this foundation to reproducible SQL, Python, business intelligence and financial modelling.</p><Link className="button button-lime" href="/projects">Explore the project roadmap <ArrowUpRight size={17}/></Link></div>
 </div></div></section></main>;
}