import type {Metadata} from "next";
import Link from "next/link";
import {ArrowUpRight,CheckCircle2,GraduationCap,Target} from "lucide-react";
import {profile} from "@/lib/content";
export const metadata:Metadata={title:"About Dennis",description:"Dennis Richard's professional background in economics, public planning, applied research and developing financial and analytical skills."};
export default function AboutPage(){return <main id="main"><section className="subhero"><div className="container"><div className="eyebrow">ABOUT / PROFESSIONAL IDENTITY</div><h1>Economics is my<br/><em>starting point.</em></h1><p>I'm a Malawi-based economist and applied research professional, working to expand the intersection of economics, financial analysis and data analytics.</p></div></section>
<section className="section section-white"><div className="container about-detail-grid"><div><div className="eyebrow">MY APPROACH</div><h2>Evidence first.<br/><span className="muted-title">Decisions next.</span></h2><p className="large-paragraph">I believe analysis earns trust through sound methods, transparent assumptions, clear communication and a willingness to acknowledge what the evidence cannot tell us.</p><p>My professional background includes infrastructure planning and monitoring at Malawi's Roads Authority, applied research and analytical consulting, and economic research. My academic training is a Bachelor of Social Sciences in Economics from the Catholic University of Malawi, awarded in 2022.</p><p>I am building more advanced technical competence in SQL, Power BI, Python, R and finance by completing substantial projects, one at a time. This site intentionally distinguishes established experience from skills still under development.</p><Link className="underlined-link" href="/work">See selected evidence <ArrowUpRight size={16}/></Link></div><div className="principles"><div><GraduationCap size={25}/><h3>Foundation</h3><p>Economics, research design, econometric reasoning and quantitative communication.</p></div><div><CheckCircle2 size={25}/><h3>Responsibility</h3><p>Validation, confidentiality, correct attribution and appropriate uncertainty.</p></div><div><Target size={25}/><h3>Direction</h3><p>Internationally relevant projects across financial planning, business intelligence and applied data science.</p></div></div></div></section>
<section className="section section-cream"><div className="container"><div className="eyebrow">KNOWLEDGE & TOOLS</div><h2>Capabilities, with context.</h2><div className="knowledge-grid"><article><span>ESTABLISHED EXPERIENCE</span><h3>Economics and research</h3><p>Research methodology, economics, Stata, SPSS, Excel, survey design, monitoring and reporting.</p></article><article><span>ADJACENT EXPERIENCE</span><h3>Evidence and operations</h3><p>Public-sector project records, reporting contributions, applied consulting and stakeholder communication.</p></article><article><span>DEVELOPING</span><h3>Financial and data systems</h3><p>SQL, Python, Power BI, R, valuation, FP&A modelling, data engineering and machine learning.</p></article></div></div></section>
<section className="section section-navy"><div className="container center-cta"><div className="eyebrow">WORK TOGETHER</div><h2>Interested in the<br/><span className="lime-title">work behind the words?</span></h2><Link href="/contact" className="button button-lime">Contact Dennis <ArrowUpRight size={17}/></Link></div></section></main>}
